execute_sequence:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: farmbot
    sequence_id:
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box
move_to:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: farmbot
    x:
      selector:
        number:
          mode: box
          step: any
    y:
      selector:
        number:
          mode: box
          step: any
    z:
      selector:
        number:
          mode: box
          step: any
    speed:
      selector:
        number:
          min: 1
          max: 100
          mode: slider
